// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj_7Yt_HZVPDJW3p7MlAWimvxh0T7yvZ0',
    appId: '1:556853245697:web:25186b989b1b7f85f4cd00',
    messagingSenderId: '556853245697',
    projectId: 'vistoria-cttu',
    authDomain: 'vistoria-cttu.firebaseapp.com',
    storageBucket: 'vistoria-cttu.firebasestorage.app',
    measurementId: 'G-FJ2D9HVM90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs_wLsC7KO0XQ_DJCo1e3d31ZGbxr9zFA',
    appId: '1:556853245697:android:8a89158b979f2616f4cd00',
    messagingSenderId: '556853245697',
    projectId: 'vistoria-cttu',
    storageBucket: 'vistoria-cttu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC1clfYmTNtp2u9N4-2C-QmgYOA5ebEEk',
    appId: '1:556853245697:ios:46beb1a2e979141bf4cd00',
    messagingSenderId: '556853245697',
    projectId: 'vistoria-cttu',
    storageBucket: 'vistoria-cttu.firebasestorage.app',
    iosBundleId: 'com.example.vistoriaCttu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC1clfYmTNtp2u9N4-2C-QmgYOA5ebEEk',
    appId: '1:556853245697:ios:46beb1a2e979141bf4cd00',
    messagingSenderId: '556853245697',
    projectId: 'vistoria-cttu',
    storageBucket: 'vistoria-cttu.firebasestorage.app',
    iosBundleId: 'com.example.vistoriaCttu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj_7Yt_HZVPDJW3p7MlAWimvxh0T7yvZ0',
    appId: '1:556853245697:web:00fd776b105f1da1f4cd00',
    messagingSenderId: '556853245697',
    projectId: 'vistoria-cttu',
    authDomain: 'vistoria-cttu.firebaseapp.com',
    storageBucket: 'vistoria-cttu.firebasestorage.app',
    measurementId: 'G-972V5LBN6J',
  );
}
